version: "3.8"

services:
  db.cba:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cctmcctm

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/log/:/var/log/nginx
      - ./nginx/ssl/:/etc/nginx/certs
